# Generated by Django 5.0.3 on 2024-03-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_receiverfilemodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverfilemodel',
            name='file',
            field=models.FileField(upload_to='receiver'),
        ),
        migrations.AlterField(
            model_name='senderfilemodel',
            name='file',
            field=models.FileField(upload_to='sender'),
        ),
    ]
