# Generated by Django 5.0.3 on 2024-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_receiverfilemodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderfilemodel',
            name='esp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='senderfilemodel',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
