# Generated by Django 5.0.3 on 2024-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_senderfilemodel_esp_senderfilemodel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderfilemodel',
            name='port',
            field=models.PositiveIntegerField(choices=[(465, '465 (Secure - Recommended)'), (587, '587 (Secure - STARTTLS'), (25, '25 (Unsecure - Not Recommended)')], default=465),
        ),
    ]
