# Generated by Django 5.0.3 on 2024-03-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_receivermodel_file_alter_sendermodel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receiverModel',
        ),
        migrations.DeleteModel(
            name='senderModel',
        ),
    ]
